#ifndef SAKURAFRPCOMMON_GLOBAL_H
#define SAKURAFRPCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef SAKURAFRPCOMMON_LIB
# define SAKURAFRPCOMMON_EXPORT Q_DECL_EXPORT
#else
# define SAKURAFRPCOMMON_EXPORT Q_DECL_IMPORT
#endif

#endif // SAKURAFRPCOMMON_GLOBAL_H
